---
- name: Install Composer
  get_url:
    url: https://getcomposer.org/composer.phar
    dest: /usr/local/bin/composer
    mode: 0755

- name: Composer Self Update
  shell: /usr/local/bin/composer self-update
